version: 1
update_configs:
  - package_manager: "rust:cargo"
    directory: "/"
    update_schedule: "live"
    version_requirement_updates: "off"
    allowed_updates:
    - match:
        update_type: "security"
    - match:
        dependency_type: "direct"
